### ISSUE TITLE
Even with .COM tld getting results for local Google URL

### ISSUE THREAD

**Issue by nsrivastava2** [MarioVilas/google#10]
Hi, 

I was trying to use the script for parsing the results but I am facing issues when I try to use the TLD as COM. The results in the parser are being shown for the local Google URL (in my case .co.in). 

Can you please help. 

Regards, 

Nitin

**Comment by MarioVilas** [comment]
I believe the .com domain always gets "translated" to your local one. I'm not sure this can be avoided :(

**Comment by landgenoot** [comment]
Use http://www.google.com/ncr (no country redirect)
