### ISSUE TITLE
Too long search

### ISSUE THREAD

**Issue by comm1x** [MarioVilas/google#16]
Thank you author for your working, great library. But.. it so long.
Simple search request executes about 3 seconds, while other libraries (for example, PyGoogler) takes about 1 seconds.

**Comment by MarioVilas** [comment]
Hi!

The delay is simply a pause between HTTP requests to make sure Google
doesn't block your IP - try reducing it for faster searches. Note however
that this library is not using any official Google API to work, so you may
experience problems if you try to make too many HTTP requests (in
particular the Captcha will pop up and of course the library won't be able
to solve it).

Cheers,
/Mario

On Tue, Dec 8, 2015 at 5:53 PM, Pavel Shorokhov <notifications@github.com>
wrote:

> Thank you author for your working, great library. But.. it so long.
> Simple search request executes about 3 seconds, while other libraries (for
> example, PyGoogler) takes about 1 seconds.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MarioVilas/google/issues/16>.
>



-- 
“There's a reason we separate military and the police: one fights the enemy
of the state, the other serves and protects the people. When the military
becomes both, then the enemies of the state tend to become the people.”
