### ISSUE TITLE
BeautifulSoup complains about parser

### ISSUE THREAD

**Issue by fxfitz** [MarioVilas/google#19]
To be completely honest, I have no idea why BeautifulSoup is yelling at my on my normal usage of your library, but I get it the first time I try to iterate through the generator that search() returns.

It looks to me like you're calling it [correctly](https://github.com/MarioVilas/google/blob/master/google/__init__.py#L283-L287), or at least using it how  the error message indictates, so something must be wrong... ?

Any thoughts?

Ideally I'd like to squash this error message.

```
No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")
```

**Comment by fxfitz** [comment]
Oooh, it looks like your recent commit (e211d1d5570b0844375f79ec3ac2a29e1c858337) fixes this.  Can you push an updated version to PyPI?

**Comment by fxfitz** [comment]
@MarioVilas A friendly ping! :-)

**Comment by MarioVilas** [comment]
Oops, sorry :) I'll update PyPy.
