### ISSUE TITLE
Search returning different umber of results than specified 

### ISSUE THREAD

**Issue by FaisalCoder** [MarioVilas/google#9]
Hey,

I have been using your code for my undergrad research thesis and it is working fine. However i am having an issue. the search function returns more than the specified urls - 

search(query,lang='en',stop=10,pause=3.0) - should return 10 results but sometimes it returns 9,14,6 results.

**Comment by MarioVilas** [comment]
Hi! Thanks for the report and for using the library :)

I've no idea what Google does with the parameters I send it. All the Python code does is pass on the parameters to the Google Search legacy API and to be perfectly honest I'm amazed it still works, that API has been deprecated for many years :D 

I know some other parameters seems to be downright ignored, or stop working when combined with other parameters.

If you really need to split results in groups of 10 I'd suggest feeding all results (no matter how many) into a list and then at the end of your search slice the list in groups of ten. That way your script will keep working regardless of what Google returns.

Good luck with your thesis! :)

**Comment by FaisalCoder** [comment]
I found the solution only_standard parameter in search needs to be set to true.

A little off the topic can you help me with this problem - 

I need to run a lot of google search queries (for the thesis) in short time.Doing it through my machine is raising HTTP error 503  most probably because of the large number of requests to google search. can u suggest me a way to run large nos of queries on google search without getting 503 error.

Do you by any chance know of some free online resource/website that can allow me to do the same

Thanks and regards,
Faisal

**Comment by MarioVilas** [comment]
Well, I'd recommend using proxies or multiple machines to spread out the queries. But other than that I can't think of a way to bypass this, sorry. :(

**Comment by FaisalCoder** [comment]
Thanks, 

BTW, I am looking for using multiple instances of Windows Azure for doing the same
